version: '3'

services:
  nginx:
    build: ./nginx
    container_name: core-nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - ..:/var/www/vhosts/core
      - ./nginx/core.conf:/etc/nginx/conf.d/core.conf
    depends_on:
      - php

  php:
    container_name: core-php
    build: ./php
    volumes:
      - ..:/var/www/vhosts/core

networks:
  default:
    external:
      name: core
